name: Python steps one by one
on: [push]
jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
     - name: Step 1 - define Python version
       run: python  --version
     - name: Step 2 - Hello from python
       run: python -c 'print("Hi")'
     - name: Step 3 - Calculation from python
       run: python -c 'print(9+10)'
     - name: Fita custom actions 
       run: python -c 'print("Jobs done")'
     - name: Install NLP libary 
       run: pip install lingua-language-detector
